demo/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,checkoutView,ProductView,PaymentView,OrderView
from cart.views import add_to_cart,remove_from_cart,CartView ,decreaseCart
# for builtin views
from django.contrib.auth import views as auth_views

app_name = 'demo'

urlpatterns = [
    path('',home.as_view(),name='demo'),
    path('add/<slug>',add_to_cart,name='cart'),
    path('cart/',CartView,name='cart-home'),
    path('remove/<slug>',remove_from_cart,name='remove'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('product/<slug>',ProductView.as_view(),name='products'),
    path('checkout/',checkoutView.as_view(),name='checkout'),
    path('payment/<payment_option>',PaymentView.as_view(),name='payment'),
    path('orders/',OrderView.as_view(),name='order'),
    ]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo.urls',namespace='demo')),
    path('accounts/',include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from demo.models import Product,Address,Payment
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

#cart model
class Cart(models.Model):
    user =  models.ForeignKey(User,on_delete=models.CASCADE)
    item = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} of {self.item.name}'

        # Getting total price
    def get_total(self):
        total = self.item.price*self.quantity
        floatTotal = float("{0:.2f}".format(total))
        return floatTotal

# Order Model
class Ord(models.Model):
    orderItems = models.ManyToManyField(Cart)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    Address = models.ForeignKey(Address,on_delete=models.SET_NULL, blank=True,null=True)
    payment = models.ForeignKey(Payment,on_delete=models.SET_NULL, blank=True,null=True)


    def __str__(self):
        return self.user.username

    def get_totals(self):
        total = 0
        for order_item in self.orderItems.all():
            total += order_item.get_total()
        return total
    # To Get Total Quantity of items in Order
    def get_quantity(self):
        total = 0
        for order_item in self.orderItems.all():
            total+= order_item.quantity
        return total

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from demo.models import Product
from .models import Cart,Ord
from django.contrib import messages


# Create your views here.

#add to cart function
def add_to_cart(request,slug):
    item = get_object_or_404(Product,slug=slug)
    if not request.user.is_authenticated:
        messages.info(request,f"Please Login to add {item} in your cart")
        return redirect("account_login")
    order_item,created = Cart.objects.get_or_create(
    item = item,
    user = request.user
    )
    order_qs = Ord.objects.filter(user=request.user,ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderItems.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request,f"{item.name} quantity has updated.")
            return redirect("demo:cart-home")
        else:
            order.orderItems.add(order_item)
            messages.info(request,f"{item.name} is added to your cart.")
            return redirect("demo:demo")
    else:
        order = Ord.objects.create(
        user = request.user
        )
        order.orderItems.add(order_item)
        messages.info(request,f"{item.name} is added to your cart.")
        return redirect("demo:demo")



# Cart View function
def CartView(request):
    if not request.user.is_authenticated:
        messages.info(request,f"Please Login to continue.")
        return redirect("account_login")
    user = request.user
    carts = Cart.objects.filter(user=user)
    orders = Ord.objects.filter(user=user,ordered=False)
    if  orders.exists():    # Add  carts.exists() or
        order = orders[0]
        return render(request,'cart/home.html',{'carts':carts,'order':order})

    else:
        messages.warning(request,"You do not have any item in cart.")
        return redirect("demo:demo")

# remove from cart function
def remove_from_cart(request,slug):
    item = get_object_or_404(Product,slug=slug)
    order_qs = Ord.objects.filter(
    user=request.user,
    ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderItems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else :
                order.orderItems.remove(order_item)
                order_item.delete()
            messages.info(request, f"{item.name} quantity has updated.")
            return redirect("demo:cart-home")
        else:
            messages.info(request, f"{item.name} quantity has updated.")
            return redirect("demo:cart-home")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("demo:cart-home")

# Remove Item from cart function
def decreaseCart(request,slug):
    item = get_object_or_404(Product,slug=slug)
    order_qs = Ord.objects.filter(
    user=request.user,
    ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.orderItems.filter(item__slug=item.slug).exists():
            order_item = Cart.objects.filter(
                item=item,
                user=request.user
            )[0]
            order.orderItems.remove(order_item)
            order_item.delete()
            messages.info(request, f"{item.name} removed from your cart.")
            return redirect("demo:cart-home")
        else:
            messages.info(request, f"You do not have {item.name} in your order.")
            return redirect("demo:demo")
    else:
        messages.info(request, "You do not have an active order.")
        return redirect("demo:demo")

cart/templates/cart/home.html
{% extends 'demo/base.html' %}
{% block content %}
<div class="container my-5">
    <div class="my-5">
        <h2>You Cart</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in carts %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ cart.item.name }}</td>
                <td>
                  <a href="{% url 'demo:remove' cart.item.slug %}">
                    <span class="badge badge-danger"><i class="fas fa-minus"></i></span></a>
                  {{ cart.quantity }}
                  <a href="{% url 'demo:cart' cart.item.slug %}">
                    <span class="badge badge-success"><i class="fas fa-plus"></i></span></a>
                </td>
                <td>Rs. {{ cart.get_total }} </td>
                <td><a href="{% url 'demo:decrease-cart' cart.item.slug %}" class="btn btn-sm btn-danger">Remove from Cart</a></td>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td>Rs. {{ order.get_totals| floatformat }}</td>
            </tr>
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right ">
									<a href="{% url 'demo:demo' %}" class="btn btn-warning m-4"> Continue Shopping </a>
                  <a href="{% url 'demo:checkout' %}" class="btn btn-success m-4"> Proceed to Checkout </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}