demo/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,checkoutView,ProductView,PaymentView,OrderView
from cart.views import add_to_cart,remove_from_cart,CartView ,decreaseCart
# for builtin views
from django.contrib.auth import views as auth_views

app_name = 'demo'

urlpatterns = [
    path('',home.as_view(),name='demo'),
    path('add/<slug>',add_to_cart,name='cart'),
    path('cart/',CartView,name='cart-home'),
    path('remove/<slug>',remove_from_cart,name='remove'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('product/<slug>',ProductView.as_view(),name='products'),
    path('checkout/',checkoutView.as_view(),name='checkout'),
    path('payment/<payment_option>',PaymentView.as_view(),name='payment'),
    path('orders/',OrderView.as_view(),name='order'),
    ]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo.urls',namespace='demo')),
    path('accounts/',include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings

# Create your models here.

#Category Model
class Category(models.Model):
    title = models.CharField(max_length=100)
    primaryCategory = models.BooleanField(default=False)

    def __str__(self):
        return self.title

#Product Model
class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    slug = models.SlugField()
    previewText = models.TextField(max_length=100,verbose_name='PreviewText')
    description = models.CharField(max_length=200,verbose_name='Description')
    price = models.FloatField()
    quantity = models.IntegerField(default=1)
    #timeStamp = models.DateTimeField()
    thumbnail = models.ImageField(upload_to='products/',default='/products/default.png')

    def __str__(self):
        return self.name

    def get_add_to_cart_url(self):
        return reverse("demo:cart", kwargs = {
        'slug' : self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("demo:remove", kwargs={
        'slug' : self.slug
        })

# Address Model
class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    Name = models.CharField(max_length=100)
    House_no = models.CharField(max_length=100)
    Area = models.CharField(max_length=100)
    Zip = models.IntegerField()
    City = models.CharField(max_length=20)
    State = models.CharField(max_length=20)
    Same_Billing_Address = models.BooleanField()

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    amount = models.FloatField()
    order_id = models.CharField(max_length=50)
    timeStamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def get_payment_url(self):
        return reverse("demo:payment",kwargs={
        'slug': self.slug
        })

demo/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

pay_choice = (
('dc','Debit Card'),
('cc','Credit Card'),
('pp','Paypal'),
('sp','Stripe'),
)

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['email','password1','password2']

# change value with placeholder
class CheckoutForm(forms.Form):
    Name = forms.CharField(widget=forms.TextInput(attrs={'value':'Faizan'}))
    House_no = forms.CharField(widget=forms.TextInput(attrs={'value':'1221'}))
    Area = forms.CharField(widget=forms.TextInput(attrs={'value':'Sector 31'}))
    City = forms.CharField(widget=forms.TextInput(attrs={'value':'Gurgaon'}))
    State = forms.CharField(widget=forms.TextInput(attrs={'value':'Haryana'}))
    Zip = forms.IntegerField(widget=forms.TextInput(attrs={'value':'122001'}))
    Payment_option = forms.ChoiceField(widget=forms.RadioSelect(attrs={'checked':'checked'}),choices=pay_choice)
    Same_Billing_Address = forms.BooleanField(widget=forms.CheckboxInput(),required=False)

demo/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,View
from demo.models import Product,Category,Address,Payment
from cart.models import Cart,Ord
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import UserRegistrationForm,CheckoutForm
from django.contrib import messages
from django.conf import settings
import stripe

# Create your views here.

# Home View
class home(ListView):
    model = Product
    template_name = 'demo/home.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['cat_list'] = Category.objects.all()
        return context

# Checkout View
class checkoutView(View):
    def get(self,*args,**kwargs):
        form = CheckoutForm()
        user = self.request.user
        orders = Ord.objects.filter(user=user,ordered=False)
        if orders.exists():
            order = orders[0]
            context = {
            'form' : form ,
            'carts' : Cart.objects.filter(user=user) ,
            'order' : order
            }
            return render(self.request,'demo/checkout-page.html',context)
        else:
            messages.warning(self.request,"You do not have any active order. Continue Shopping !!!")
            return redirect('demo:demo')
    def post(self,*args,**kwargs):
        form = CheckoutForm(self.request.POST or None)
        orders = Ord.objects.filter(user=self.request.user,ordered=False)
        if form.is_valid():
            Name = form.cleaned_data.get('Name')
            House_no = form.cleaned_data.get('House_no')
            Area = form.cleaned_data.get('Area')
            Zip = form.cleaned_data.get('Zip')
            Same_Billing_Address = form.cleaned_data.get('Same_Billing_Address')
            City = form.cleaned_data.get('City')
            State = form.cleaned_data.get('State')
            shippingAddress = Address(
            user = self.request.user ,
            Name = Name ,
            House_no = House_no,
            Area = Area,
            City = City,
            State = State,
            Zip = Zip,
            Same_Billing_Address = Same_Billing_Address,
            )
            shippingAddress.save()
            payment_option = form.cleaned_data.get('Payment_option')
            if payment_option != 'sp':
                messages.warning(self.request,"Under Maintainence.Please Select Stripe Payment option.")
                return redirect("demo:checkout")
        return redirect("/payment/stripe")


# Product View
class ProductView(DetailView):
    model = Product
    template_name = 'demo/product-page.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        return context

stripe.api_key = settings.STRIPE_SECRET_KEY


# Payment View Function
class PaymentView(View):
    def get(self,*args,**kwargs):
        return render(self.request,"demo/payment.html")
    def post(self,*args,**kwargs):
        token = self.request.POST.get('stripeToken')
        user = self.request.user
        order = Ord.objects.get(user=user,ordered=False)
        amount = int(order.get_totals())
        try:
            # Use Stripe's library to make requests...
            charge = stripe.Charge.create(
            amount = amount,
            currency = 'usd',
            source=token
            )

            # Updating payment in db
            payment = Payment()
            payment.user = self.request.user
            payment.amount = amount
            payment.order_id = charge['id']
            payment.save()

            # Updating order in db
            order.payment = payment
            order.ordered = True
            order.save()

            #Remove from cart
            order_items = Cart.objects.filter(user=user)[0]
            order_items.delete()


            messages.success(self.request, "Your order is successfully placed.")
            redirect("/")
        except stripe.error.CardError as e:
            # Since it's a decline, stripe.error.CardError will be caught
            body = e.json_body
            err = body.get('error',{})
            messages.warning(self.request, f"{err.get('message')}")
        except stripe.error.RateLimitError as e:
            # Too many requests made to the API too quickly
            messages.warning(self.request, "Rate limit error")
        except stripe.error.InvalidRequestError as e:
            # Invalid parameters were supplied to Stripe's API
            messages.warning(self.request, "Invalid parameters")
        except stripe.error.AuthenticationError as e:
            # Authentication with Stripe's API failed
            # (maybe you changed API keys recently)
            messages.warning(self.request, "Not Authenticated")
        except stripe.error.APIConnectionError as e:
            # Network communication with Stripe failed
            messages.warning(self.request, "Network error")
        except stripe.error.StripeError as e:
            messages.warning(self.request, "Something went wrong. You will not charged. Please try again.")
        except Exception as e:
            # Something else happened, completely unrelated to Stripe
            messages.warning(self.request, "A serious error occurred. We have been notifed.")
        return redirect("/")

# Order View
class OrderView(View):
    model = Ord
    def get(self,*args,**kwargs):
        user = self.request.user
        context = {
        'orders' : Ord.objects.filter(user=user,ordered=True),
        'payment' : Payment.objects.filter(user=user)
        }
        return render(self.request,"demo/order.html",context)

demo/templates/demo/base.html
{% load static %}
{% load cart_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=devicehome-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }
    .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
  }
    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
  <title>{% block head_title %} Jibz Store {% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
</head>
<body>
  {% block body %}

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'demo:demo' %}" >
          <strong class="blue-text">Jibz Store</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="{% url 'demo:demo' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'demo:checkout' %}" >Checkout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'demo:order' %}" >Orders</a>
            </li>
            {% endif %}
          </ul>

          <!-- Right -->
          {% if request.user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'demo:cart-home' %}">
              <i class="fas fa-shopping-cart"></i>Cart
              <span class="badge badge-warning">{{ request.user| cart_total }}</span>
            </a>
          </li>
            <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">{{ request.user }}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
            </div>
          </div>
          {% else %}
            <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'demo:cart-home' %}">
              <i class="fas fa-shopping-cart"></i>Cart
              <span class="badge badge-warning"><b>0</b></span>
            </a>
          </li>
            <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My Account
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'account_signup' %}">Register</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_login' %}">Login</a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="p-1 my-5"></div>
        <!-- Navbar -->
        {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong><button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
      {% endfor %}
      {% endif %}


    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}

</main>

<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="embed-responsive embed-responsive-4by3">
           <img alt="Card image cap" class="card-img-top embed-responsive-item rounded" src="/media/specialOffer.png" />
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-sm pt-1">

        <!--Image-->
          <p class="text-sm-left"><strong class="text-success">Best Offers </strong>
            <br>Cheaper prices than your local supermarket, great cashback offers to top it off.</p>
          <a href="{% url "demo:demo" %}">
            <div class="mask rgba-white-light"></div>
          </a>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="embed-responsive embed-responsive-4by3">
           <img alt="Card image cap" class="card-img-top embed-responsive-item rounded" src="/media/cart.jpg" />
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-sm pt-1">

        <!--Image-->
          <p class="text-sm-left"><strong class="text-warning">Wide Assesment</strong>
            <br>Choose from 5000+ products across food, personal care, household & other categories.</p>
          <a href="{% url "demo:demo" %}">
            <div class="mask rgba-white-light"></div>
          </a>

      </div>
      <!--Grid column-->



      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="embed-responsive embed-responsive-4by3">
           <img alt="Card image cap" class="card-img-top embed-responsive-item rounded" src="/media/return.png" />
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-sm pt-1">

        <!--Image-->
          <p class="text-sm-left"><strong class="text-primary">Easy Returns.</strong>
            <br>Not satisfied with a product? Return it at the doorstep & get a refund within hours.</p>
          <a href="{% url "demo:demo" %}">
            <div class="mask rgba-white-light"></div>
          </a>

      </div>
      <!--Grid column-->



    </div>
    <!--Grid row-->

  </div>
  <!-- Footer Elements -->




  <hr>

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/demo"> Jibz Store </a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

demo/templates/demo/checkout-page.html
{% extends "demo/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

  <!--Main layout-->
<main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form method="POST" class='card-body'>
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>
          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{ order.get_quantity }}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            {% for cart in carts %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ cart.item.name }} * {{ cart.quantity }}</h6>
                <small class="text-muted">{{ cart.item.description }}</small>
              </div>
              <span class="text-muted">Rs.{{ cart.get_total }}</span>
            </li>
            {% endfor %}
            <!-- Promo Code -->
            <!--
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-Rs.5</span>
            </li>-->
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (Rs)</span>
              <strong>Rs.{{ order.get_totals }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock %}

demo/templates/demo/order.html
{% extends "demo/base.html"%}
{% block content %}
<div class="container my-5">
    <div class="my-5">
        <h2>You Orders</h2>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Order ID</th>
                <th scope="col">Amount</th>
            </tr>
        </thead>
        <tbody>
            {% for pay in payment %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>

                    <td>{{ pay.user }}</td>
                <td>{{ pay.order_id }}</td>
                <td>Rs. {{ pay.amount }} </td>
            </tr>
            {% endfor %}
            <tr>
                <th scope="row"></th>
                <td colspan="4" class="text-right ">
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

demo/templates/demo/payment.html
<html>
<head>
<title> Payment </title>
</head>
<style>
/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>
  <body>
    <h2 class="my-5 h2 text-center">Payment</h2>
            <!--Card content-->
            <script src="https://js.stripe.com/v3/"></script>

            <form method="post" id="payment-form">
              {% csrf_token %}
              <div class="form-row">
                <label for="card-element">
                  Credit or debit card
                </label>
                <div id="card-element">
                  <!-- A Stripe Element will be inserted here. -->
                </div>

                <!-- Used to display form errors. -->
                <div id="card-errors" role="alert"></div>
              </div>

              <button>Submit Payment</button>
            </form>

<script>// Create a Stripe client.
var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>
</body>
</html>

demo/templates/demo/product-page.html
{% extends "demo/base.html"%}
{% block content %}
<body>


  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="/media/{{ object.thumbnail }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->
        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.category }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">
                {% if object.dis_price %}
                <del>Rs {{ object.dis_price }}</del>
              </span>
              {% else %}
              <span>Rs {{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary">Add to Cart<i class="fas fa-shopping-cart ml-1"></i></a>
            {% if user.is_authenticated %}
            <a href="{% url 'demo:decrease-cart' object.slug %}" class="btn btn-danger">Remove from Cart<i class="fas fa-shopping-cart ml-1"></i></a>
            {% endif %}
          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>{{ object.previewText }}</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
<hr>
<h5 class="my-4 h5 text-center">Similar Products</h5>
      <!--Grid row-->
      <div class="row wow fadeIn">


      {% for product in products %}
        {% if product.name != object.name %}
          {% if product.category == object.category %}
              <!--Grid column-->
              <div class="col-lg-4 mb-4 border">
                <div class="embed-responsive embed-responsive-4by3">
                   <img alt="Card image cap" class="card-img-top embed-responsive-item" src="/media/{{ product.thumbnail }}" />
                   <a href="{{ product.slug }}">
                </div>
                <p class="text-muted text-center">{{ product.name }}</p>

              </div>
          {% endif %}
        {% endif %}
      {% endfor %}



      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}